//LOGIN de USUARIO DE TYPE
export const PETITION_LOGIN = "PETITION_LOGIN";
export const PETITION_AUTHENTICATED = "PETITION_AUTHENTICATED";
export const PETITION_AUTH = "PETITION_AUTH";

//START PROCESS START
export const PETITION_READ_COMPANY = "PETITION_READ_COMPANY"; //
export const PETITION_READ_BUSINESS = "PETITION_READ_BUSINESS"; //

//TOOLS
export const TOOL_SELECTION_INFORMATION_COMPANY =
  "TOOL_SELECTION_INFORMATION_COMPANY";
export const TOOL_SELECTION_INFORMATION_BUSINESS =
  "TOOL_SELECTION_INFORMATION_BUSINESS";
export const TOOL_SELECTION_READ = "TOOL_SELECTION_READ";
export const TOOL_SELECTION = "TOOL_SELECTION";
export const TOOL_SELECTION_READ_ALL='TOOL_SELECTION_READ_ALL';

// //COMPANY PROCESS COMPANY
export const COMPANY_READ = "COMPANY_READ"; //
export const COMPANY_SAVE_COMPANY = "COMPANY_SAVE_COMPANY"; //
export const COMPANY_MODAL_LOGO = "COMPANY_MODAL_LOGO"; //
export const COMPANY_MODAL_LOGAL_VIEW = "COMPANY_MODAL_LOGAL_VIEW"; //
export const COMPANY_MODAL_UPDATE = "COMPANY_MODAL_UPDATE"; //

export const COMPANY_UPDATE = "COMPANY_UPDATE";
export const COMPANY_DELETE = "COMPANY_DELETE";
export const COMPANY_UPDATE_IMG = "COMPANY_UPDATE_IMG";

export const COMPANY_SAVE_COMPANY_UPDATE = "COMPANY_SAVE_COMPANY_UPDATE";
export const COMPANY_DIRECTION_LOGO = "COMPANY_DIRECTION_LOGO";

// //BUSINESS PROCESS
export const BUSINESS_CREATE = "BUSINESS_CREATE";
export const BUSINESS_READ = "BUSINESS_READ";
export const BUSINESS_UPDATE = "BUSINESS_UPDATE";
export const BUSINESS_MODAL_UPDATE = "BUSINESS_MODAL_UPDATE";
export const BUSINESS_ARRAY_UPDATE = "BUSINESS_ARRAY_UPDATE";
export const BUSINESS_DELETE = "BUSINESS_DELETE";

//USER  PROCESS
export const USER_CREATE = "USER_CREATE";
export const USER_READ = "USER_READ";
export const USER_UPDATE = "USER_UPDATE";
export const USER_MODAL_UPDATE = "USER_MODAL_UPDATE";
export const USER_ARRAY_UPDATE = "USER_ARRAY_UPDATE";
export const USER_DELETE = "USER_DELETE";

//PROCESS DOSAGE
export const DOSAGE_CREATE = "DOSAGE_CREATE";
export const DOSAGE_READ = "DOSAGE_READ";
export const DOSAGE_UPDATE = "DOSAGE_UPDATE";
export const DOSAGE_MODAL_UPDATE = "DOSAGE_MODAL_UPDATE";
export const DOSAGE_ARRAY_UPDATE = "DOSAGE_ARRAY_UPDATE";
export const DOSAGE_DELETE = "DOSAGE_DELETE";
export const DOSAGE_READ_CURRENT = "DOSAGE_READ_CURRENT";
export const DOSAGE_SELECTION = "DOSAGE_SELECTION";

//PROCESS MEASURE
export const MEASURE_CREATE = "MEASURE_CREATE";
export const MEASURE_READ = "MEASURE_READ";
export const MEASURE_UPDATE = "MEASURE_UPDATE";
export const MEASURE_MODAL = "MEASURE_MODAL";
export const MEASURE_MODAL_UPDATE = "MEASURE_MODAL_UPDATE";
export const MEASURE_ARRAY_UPDATE = "MEASURE_ARRAY_UPDATE";
export const MEASURE_DELETE = "MEASURE_DELETE";

//PROCESS PRODUCT
export const PRODUCT_CREATE = "PRODUCT_CREATE";
export const PRODUCT_READ = "PRODUCT_READ";
export const PRODUCT_UPDATE = "PRODUCT_UPDATE";
export const PRODUCT_MODAL_UPDATE = "PRODUCT_MODAL_UPDATE";
export const PRODUCT_ARRAY_UPDATE = "PRODUCT_ARRAY_UPDATE";
export const PRODUCT_DELETE = "PRODUCT_DELETE";

//PROCESS BILL UNIQUE
export const BILL_MODAL_UNIQUE = "PRODUCT_MODAL_BILL_UNIQUE";
export const BILL_ARRAY_PRODUCT = "BILL_ARRAY_PRODUCT";
export const BILL_TOTAL_PRODUCT='BILL_TOTAL_PRODUCT';
export const BILL_ARRAY_RESET='BILL_ARRAY_RESET';
export const BILL_MODAL_SELECTION='BILL_MODAL_SELECTION'
export const BILL_ARRAY_BILL_PRINT='BILL_ARRAY_BILL_PRINT';
export const BILL_ARRAY_SELECTION_RESET='BILL_ARRAY_SELECTION_RESET';

//PROCESS BILL ALL
export const BILL_DRAWER_TOP='BILL_DRAWER_TOP';
export const BILL_ARRAY_PRODUCT_SELECTION ='BILL_ARRAY_PRODUCT_SELECTION'
export const BILL_ARRAY_PRODUCT_SET='BILL_ARRAY_PRODUCT_SET';

//PROCESS ADMIN BILL
export const BILL_TABLE_READ = 'BILL_TABLE_READ';
export const BILL_TABLE_READ_COPY ='BILL_TABLE_READ_COPY';
export const BILL_TABLE_UPDATE_CONDITION='BILL_TABLE_UPDATE_CONDITION';