//LOGIN de USUARIO DE TYPE
export const PETITION_LOGIN = "PETITION_LOGIN";

//LOGIN AUTENTIFICACION
export const ERROR_LOGUEO = "ERROR_LOGUEO";
export const PETITION_AUTHENTICATED = "PETITION_AUTHENTICATED";
export const PETITION_AUTH='PETITION_AUTH';
//START PROCESS START
export const PETITION_READ_COMPANY = "PETITION_READ_COMPANY";
export const PETITION_READ_BUSINESS = "PETITION_READ_BUSINESS";

// //COMPANY PROCESS COMPANY
export const COMPANY_CREATE = "COMPANY_CREATE"; //
export const COMPANY_READ = "COMPANY_READ";
export const COMPANY_UPDATE = "COMPANY_UPDATE";
export const COMPANY_DELETE = "COMPANY_DELETE";
export const COMPANY_UPDATE_IMG = "COMPANY_UPDATE_IMG";

export const COMPANY_SAVE_COMPANY = "COMPANY_SAVE_COMPANY";
export const COMPANY_SAVE_COMPANY_UPDATE = "COMPANY_SAVE_COMPANY_UPDATE";
export const COMPANY_SAVE_ID_COMPANY_UPDATE='COMPANY_SAVE_ID_COMPANY_UPDATE';

export const COMPANY_MODAL_LOGO ='COMPANY_MODAL_LOGO';
export const COMPANY_DIRECTION_LOGO='COMPANY_DIRECTION_LOGO';
// //BUSINESS PROCESS
